// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdNjuVF9uS7mWbdT6zNeoSIaQStbhA3DE',
    appId: '1:533617235819:web:0c40171460f3c62364de2e',
    messagingSenderId: '533617235819',
    projectId: 'domestiko-3beed',
    authDomain: 'domestiko-3beed.firebaseapp.com',
    databaseURL: 'https://domestiko-3beed-default-rtdb.firebaseio.com',
    storageBucket: 'domestiko-3beed.appspot.com',
    measurementId: 'G-9YM9YYMMW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-FRkWsiAjibh0-e2QLNyV-nhwyJNwJrI',
    appId: '1:533617235819:android:41cf20d3b630992a64de2e',
    messagingSenderId: '533617235819',
    projectId: 'domestiko-3beed',
    databaseURL: 'https://domestiko-3beed-default-rtdb.firebaseio.com',
    storageBucket: 'domestiko-3beed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcy0DKcj-D3Y67QPgem3d0OxhM9bIK-QY',
    appId: '1:533617235819:ios:1c2eb1dc91eebdd464de2e',
    messagingSenderId: '533617235819',
    projectId: 'domestiko-3beed',
    databaseURL: 'https://domestiko-3beed-default-rtdb.firebaseio.com',
    storageBucket: 'domestiko-3beed.appspot.com',
    iosClientId: '533617235819-u1dfb6ottf49ole2hun7rof5tu5n3q9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.domestiko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcy0DKcj-D3Y67QPgem3d0OxhM9bIK-QY',
    appId: '1:533617235819:ios:1c2eb1dc91eebdd464de2e',
    messagingSenderId: '533617235819',
    projectId: 'domestiko-3beed',
    databaseURL: 'https://domestiko-3beed-default-rtdb.firebaseio.com',
    storageBucket: 'domestiko-3beed.appspot.com',
    iosClientId: '533617235819-u1dfb6ottf49ole2hun7rof5tu5n3q9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.domestiko',
  );
}
